'use strict';

module.exports = {
  '@primary-color': '#0d7b7b',
  '@primary-1': '#193D37',
  '@body-background': '#0a0f0e',
  '@component-background': '#172422',
  '@font-family':
    '"Microsoft Yahei", MicrosoftYaHei, "PingFang SC", "Helvetica Neue", sans-serif',
  '@text-color': '#ffebc8',
  '@text-color-secondary': '#ffebc8',
  '@border-radius-base': '2px',
  '@border-color-base': '#233431',
  '@border-color-split': '#253936',
  '@box-shadow-base': '2px 2px 0 0 rgba(0,0,0,0.50)',
  '@layout-body-background': 'transparent',
  '@layout-header-background': '#172422',
  '@layout-header-height': '30px',
  '@layout-header-padding': '0px',
  '@layout-footer-padding': '0px',
  '@input-height-base': '24px',
  '@input-color': '#fff3dd',
  '@input-bg': '#0e1a18',
  '@input-addon-bg': '#2b2d2f',
  '@input-placeholder-color': '#7B8280',
  '@menu-dark-bg': '#172422',
  '@menu-dark-submenu-bg': '#193d37',
  '@error-color': '#DC4444',
  '@table-header-bg': '#172422',
  '@table-header-text': '#7b8082',
  '@table-padding-vertical': '11px',
  '@btn-default-bg': '#136C5E',
  '@btn-default-border': 'transparent',
  '@btn-padding-sm': '2px 7px',
  '@btn-circle-size-sm': '24px',
  '@btn-primary-color': '#ffebc8',
  '@tooltip-color': '#ffebc8',
  '@tooltip-max-width': '500px',
  '@tooltip-bg': '#193d37',
  '@tooltip-arrow-width': '0px',
  '@popover-bg': '#172422',
  '@popover-arrow-width': '0px',
  '@background-color-base': '#0a0f0e',
  '@background-color-light': '#0a0f0e',
  '@checkbox-check-color': '#0a0f0e',
  '@font-size-base': '12px',
  '@font-size-sm': '10px',
  '@heading-color': '#ffebc8',
  '@disabled-color': '#888888',
  '@radio-button-active-color': '#FF9200',
  '@radio-button-bg': '#172422',
  '@radio-button-color': '#ffebc8',
  '@radio-button-hover-color': '#172422',
  '@input-hover-border-color': '#FFB000',
  '@input-border-color': '#FFB000'
};
